-- DataKite AI persistent usage analytics
-- Run this once in Supabase SQL Editor.
create table if not exists public.datakite_usage_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  user_id text,
  user_email text,
  user_name text,
  question text,
  success boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_datakite_usage_created_at on public.datakite_usage_events(created_at desc);
create index if not exists idx_datakite_usage_event_type on public.datakite_usage_events(event_type);
create index if not exists idx_datakite_usage_user_email on public.datakite_usage_events(user_email);

-- Backend uses the service-role key. Do not expose that key in frontend code.
-- Keep this table inaccessible to browser clients unless you intentionally add
-- a separate RLS policy for your own authenticated analytics workflow.
alter table public.datakite_usage_events enable row level security;
